# Generated by Django 5.0.6 on 2024-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='main_app.category'),
        ),
    ]
