# Generated by Django 5.0.6 on 2024-06-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
