# Generated by Django 5.0.6 on 2024-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_item_type_item_quantity_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_min',
            field=models.IntegerField(default=1),
        ),
    ]
