# Generated by Django 5.0.6 on 2024-06-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_historylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
        ),
    ]
