# Generated by Django 5.0.6 on 2024-07-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_quantitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantitylog',
            name='previous_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_current',
            field=models.IntegerField(default=0),
        ),
    ]
