# Generated by Django 5.0.6 on 2024-07-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
    ]
